### ISSUE TITLE
Create InterpretedExperiment class

### ISSUE THREAD

**Issue by eytan** [HubSpot/PlanOut.js#12]
There is a demo / test for the interpreter itself, but AFAIK no code that demonstrates how the two would work together (in particular, this requires some integration with the inExperiment flag that specifies whether or not the experiment should do an exposure log).  @rawls238, are you guys using the interpreter in production?  If so, perhaps this example would be easy to hack up, otherwise I could give it a shot when I have some time...  It would also be great to have the PlanOut editor use PlanOut.js instead of rely on a Python/Flask-based backend.

**Comment by rawls238** [comment]
@eytan we are mainly using the native API (with some slight modifications for internal-specific things) in production where experiment classes are stored in repositories that are shared between multiple projects mainly due to how fast it is relative to making a network request to fetch a serialized experiment, but I am slowly trying to get us to move to serialized experiment definitions so that we can do some basic automated analysis of our experiments. I will throw my InterpretedExperiment class in the repo as an example, but one of the biggest issues around dealing with serialized experiments is how to best structure things so that we can deal with serialized namespaces as well and doing this in a scalable way. I'm curious how Facebook does this at scale, but I understand if you'd be hesitant to share any details on a public forum such as this. Mind if I shoot you an email with a few questions re: serialized experiments?

**Comment by eytan** [comment]
Feel free to send me an email at eytan at fb dot com.

**Comment by rawls238** [comment]
https://github.com/HubSpot/PlanOut.js/pull/24 adds the ```InterpretedExperiment``` class to the examples
