### ISSUE TITLE
Ability to pass Experiment Instance from Props ?

### ISSUE THREAD

**Issue by SunnyGurnani** [HubSpot/PlanOut.js#43]
Experiment is getting initialized only once on the server instead of on every request.

**Comment by rawls238** [comment]
can you post some code and a bit more detail? You should be using your experiment class as a singleton so it makes sense that it's getting initialized only once on the server.

**Comment by SunnyGurnani** [comment]
How to change the Unit of Experiment Dynamically ?

I want to get unit from url params through **react-router**

I tried 
``` ExperimentSetup.registerExperimentInput('diet', routerProps.params.diet);  ```

But

**Comment by SunnyGurnani** [comment]
Problem is parameterize() function takes Experiment instance which has to be created at File level instead of component level and at File Level you don't know current user id.

**Signup.js**
```
let experiment = new MyNameSpace();

export default parameterize(experiment, ["signupText"], Component)

```

**Home.js**
```
import Signup from './Signup'

function Home(){
   return <Signup />
}

```

**Login.js**
```
loginSuccess(function(userId){
   ExperimentSetup.registerExperimentInput('userId', routerProps.params.id);
});

```

This will give an error that userId is not there which can be avoided by setting default value but when userId is set using ```ExperimentSetup.registerExperimentInput('userId', routerProps.params.id);``` It does not Changes anything since instance of Namespace was already created earlier.

**Comment by SunnyGurnani** [comment]
Let me create this bug on react-experiments I think its more related to that than Planout.js

**Comment by rawls238** [comment]
I think the issue is that the component mounts before the user id is passed through since there's basically a race condition there. This is an unfortunate challenge to doing async user id passing. Perhaps there needs to be something in react-experiments that will make the component remount when a change in the user id is detected or something. Don't have time to look into this until the 22nd due to exams, but maybe @mattrheault can be of some more assistance in the meantime
