### ISSUE TITLE
Random number generation

### ISSUE THREAD

**Issue by phykas** [HubSpot/PlanOut.js#61]
Hi guys, 
First, enjoying your library so far, and want to thank you for investing your time into porting this great library to js. I do have one question, and it's about this line:

https://github.com/HubSpot/PlanOut.js/blob/master/es6/ops/randomBase.js#L8
`hashCalculation(hash) {
    return parseInt(hash.substr(0, 13), 16);
  }`

Are you sure that should be 13, because I'm doing some C# library and using yours as a reference. When I use 15 instead of 13, I get normal probabilities also normalizing the numbers works fine as well. But with 13 this part of the code is not working for me:
`var zeroToOne = this.zeroToOneCalculation(appendedUnit);
	      return zeroToOne * (maxVal - minVal) + minVal;`
Check out the Java port is also using 15 char substring:
https://github.com/Glassdoor/planout4j/blob/master/core/src/main/java/com/glassdoor/planout4j/planout/ops/random/PlanOutOpRandom.java#L73

Also the original Facebook library is using 15:
https://github.com/facebook/planout/blob/master/python/planout/ops/random.py#L30

**Comment by phykas** [comment]
"The underlying randomization ops in the JavaScript implementation return different results for efficiency reasons."
This is probably the reason? :)

**Comment by mattrheault** [comment]
Yeah this is definitely for efficiency reasons and possibly JS's [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER), though I can't remember whether that played a factor. @rawls238 might remember better on that. 

Either way, the JS port of planout is not core compatible by default with it's sibling implementations. If you've gotta have core compatibility, then you'll need to use the [core_compatible](https://github.com/HubSpot/PlanOut.js/blob/master/dist/planout_core_compatible.min.js) bundle which has [bignumber.js](https://github.com/MikeMcl/bignumber.js/) as a dependency and performs random operations much less efficiently.

We split the core compatible bundle out because most people don't need their random operations to match the other implementations, so efficiency took precedence.

**Comment by rawls238** [comment]
Sorry I meant to respond to this. It has to do with JS's `MAX_SAFE_INTEGER` as @mattrheault mentioned. Ideally we could just use 15 here and so many headaches would be saved, but we can't so we have to resort to using `bignumber.js` to get compatibility which results in efficiency issues relative to not using the library. In your C# library you should use 15.

**Comment by eytan** [comment]
+1.

**Comment by phykas** [comment]
Thank you very much for your answer, I'll use 15 in C# then...  :)
